- name: Install cmusphinx packages
  apt: name={{ item }} default_release=stable
  with_items:
    - autoconf
    - libtool
    - automake
    - gfortran
    - g++
    - make

- name: Clone cmusphinx repo
  git: repo=https://github.com/narfman0/cmusphinx.git dest=/root/cmusphinx

- name: Build cmuclmtk
  shell: ./autogen.sh && make && make install
  args:
    chdir: /root/cmusphinx/cmuclmtk
