---
- include: packages.yml
  tags: packages

- name: Create jasper user
  user: name={{ jasper_user }} comment="jasper" shell=/bin/bash groups=audio append=yes

- name: Clone jasper repo
  git: repo=https://github.com/jasperproject/jasper-client.git dest={{ jasper_path }} version=jasper-dev
  become_user: "{{ jasper_user }}"

- include: phonetisaurus.yml
  tags: phonetisaurus

- include: pip.yml
  tags: pip

- name: Create settings directory
  file: path={{ jasper_base_path }}/.jasper state=directory
  become_user: "{{ jasper_user }}"

- name: Create settings file
  template: src=profile.yml.j2 dest={{ jasper_base_path }}/.jasper/profile.yml
  become_user: "{{ jasper_user }}"

- include: raspberrypi.yml
  tags: raspberrypi
  when: "'rasppi' in groups and '{{ ansible_hostname }}' in groups['rasppi']"

- name: Install systemd unit
  template: src=jasper.service.j2 dest=/etc/systemd/system/jasper.service

- name: Enable jasper service (manually, see ansible-modules-core #3784)
  shell: systemctl enable jasper

- name: Run jasper
  systemd: state=restarted name=jasper enabled=True
