---
- name: Add experimental repo
  shell: echo 'deb http://httpredir.debian.org/debian experimental main contrib non-free' > /etc/apt/sources.list.d/experimental.list

- name: Add testing repo
  shell: echo 'deb http://httpredir.debian.org/debian testing main' > /etc/apt/sources.list.d/testing.list

- name: Update apt
  apt: update_cache=yes

- name: Install packages
  command: apt-get install git python-dev bison libasound2-dev python-pyaudio pocketsphinx swig libpulse-dev -y

- name: Install libfst
  command: apt-get -t testing install libfst-tools -y

- name: Install experimental packages
  command: apt-get -t experimental install m2m-aligner mitlm phonetisaurus -y

- name: Install modern pip
  command: easy_install pip

- name: Create jasper user
  user: name={{ jasper_user }} comment="jasper"

- name: Clone jasper repo
  git: repo=https://github.com/jasperproject/jasper-client.git dest={{ jasper_path }}
  become_user: jasper

- name: Pip install jasper requirements
  pip: requirements="{{ jasper_path }}/client/requirements.txt"

- name: Pip install jasper specifics
  pip: name=pocketsphinx extra_args=--no-cache-dir
