---
- name: Add experimental repo
  template: src=experimental.list.j2 dest=/etc/apt/sources.list.d/experimental.list

- name: Add testing repo
  template: src=testing.list.j2 dest=/etc/apt/sources.list.d/testing.list

- name: Install packages
  apt: name={{ item }} update_cache=yes default_release=stable
  with_items:
    - git
    - bison
    - libasound2-dev
    - pocketsphinx
    - swig
    - libpulse-dev
    - espeak
    - alsa-utils
    - portaudio19-dev
    - libmad0

- name: Install testing packages
  apt: name={{ item }} default_release=testing force=yes
  with_items:
    - libfst-tools
    - python-dev
    - python-pyaudio

- name: Install experimental packages
  apt: name={{ item }} default_release=experimental force=yes
  with_items:
    - m2m-aligner
    - mitlm
    - phonetisaurus
