---
- name: Add experimental repo
  lineinfile:
    dest: /etc/apt/sources.list
    regexp: 'experimental'
    line: 'deb http://httpredir.debian.org/debian experimental main contrib non-free'

- name: Add testing repo
  lineinfile:
    dest: /etc/apt/sources.list
    regexp: 'testing'
    line: 'deb http://httpredir.debian.org/debian testing main'

- name: Create apt preference file
  template: src=preferences.j2 dest=/etc/apt/preferences

- name: Install packages
  apt: name={{ item }} update_cache=yes
  with_items:
    - git
    - bison
    - libasound2-dev
    - pocketsphinx
    - swig
    - libpulse-dev
    - espeak
    - alsa-utils
    - portaudio19-dev
    - libmad0
    - libfst-tools
    - m2m-aligner
    - mitlm
    - phonetisaurus
    - python-dev
    - python-pyaudio
