---
- name: Add experimental repo
  lineinfile:
    dest: /etc/apt/sources.list
    regexp: 'experimental'
    line: 'deb http://httpredir.debian.org/debian experimental main contrib non-free'

- name: Add testing repo
  lineinfile:
    dest: /etc/apt/sources.list
    regexp: 'testing'
    line: 'deb http://httpredir.debian.org/debian testing main'

- name: Create apt preference file
  template: src=preferences.j2 dest=/etc/apt/preferences

- name: Update cache
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade packages
  # Upgrade needed for text2wfreq issue; likely libc
  apt: upgrade=dist dpkg_options="skip-same-version"
  register: dpkg_result
  changed_when: dpkg_result.stdout.find("\n0 upgraded") == -1

- name: Install packages
  apt: name={{ item }}
  with_items:
    - git
    - bison
    - libasound2-dev
    - pocketsphinx
    - swig
    - libpulse-dev
    - espeak
    - alsa-utils
    - portaudio19-dev
    - libmad0
    - libfst-tools
    - m2m-aligner
    - mitlm
    - phonetisaurus
    - python-dev
    - python-pyaudio
