---
- name: Download pip
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /root/get-pip.py

- name: Check if pip installed
  stat:
    path: "/usr/local/bin/pip"
  register: stat_result

- name: Install recent pip
  shell: python get-pip.py
  args:
    chdir: /root
  when: stat_result.stat.exists == False

- name: Pip install jasper requirements
  pip: requirements="{{ jasper_path }}/requirements.txt"
  notify:
  - Restart jasper

- name: Pip install jasper specifics
  pip: name={{ item }} extra_args=--no-cache-dir
  with_items:
    - pocketsphinx
    - pyalsaaudio
    - slugify
    - mad
